name: authenticator_juego_responsable
description: "Authenticator | Juego Responsable - Flutter KYC Identity Verification MVP"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Design & UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10

  # Hardware & Security APIs
  camera: ^0.10.5+9
  local_auth: ^2.1.8
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2

  # Utility & State
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/auth_light.png
    - assets/images/auth_dark.png
